apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tapp-front
  name: tapp-front
  namespace: tapp-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tapp-front
  template:
    metadata:
      labels:
        app: tapp-front
    spec:
      containers:
      - image: nexus.tapp.asianaidt.com:5000/tapp/prod/tapp-front
        name: tapp-front